"""Add ParticipationHistory table

Revision ID: 7c23eac95081
Revises: f823a5a0fa14
Create Date: 2025-11-20 11:01:52.264180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c23eac95081'
down_revision: Union[str, Sequence[str], None] = 'f823a5a0fa14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participation_history',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_participation_id', sa.Integer(), nullable=False, comment='삭제될 원본 테이블의 ID (단순 매핑용)'),
    sa.Column('gender', sa.String(length=10), nullable=False, comment='사용자 성별 (male/female)'),
    sa.Column('selected_profile_name', sa.String(length=100), nullable=True, comment='선택한 프로필 이름 (예: 광수)'),
    sa.Column('selected_talent_name', sa.String(length=100), nullable=True, comment='선택한 장기자랑 이름 (예: 기타 연주)'),
    sa.Column('is_printed_profile', sa.Boolean(), nullable=False, comment='프로필 사진 인쇄 여부'),
    sa.Column('is_printed_talent', sa.Boolean(), nullable=False, comment='장기자랑 사진 인쇄 여부'),
    sa.Column('is_download_page_accessed', sa.Boolean(), nullable=False, comment='QR 스캔 후 다운로드 페이지 진입 여부'),
    sa.Column('download_count_profile', sa.Integer(), nullable=False, comment='프로필 사진 다운로드 버튼 클릭 횟수'),
    sa.Column('download_count_talent', sa.Integer(), nullable=False, comment='장기자랑 사진 다운로드 버튼 클릭 횟수'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='체험 완료 시간'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_participation_history_history_id'), 'participation_history', ['history_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participation_history_history_id'), table_name='participation_history')
    op.drop_table('participation_history')
    # ### end Alembic commands ###
