"""Initial database schema

Revision ID: f823a5a0fa14
Revises: 
Create Date: 2025-11-18 20:35:49.691898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f823a5a0fa14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_profile',
    sa.Column('profile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_name', sa.String(length=100), nullable=False, comment='프로필 이름 (예: 광수)'),
    sa.Column('gender_filter', sa.String(length=10), nullable=False, comment='매칭될 성별 (male/female)'),
    sa.Column('target_image_path', sa.String(length=512), nullable=False, comment='딥페이크 합성에 사용될 타겟 이미지 경로'),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('profile_name')
    )
    op.create_index(op.f('ix_target_profile_profile_id'), 'target_profile', ['profile_id'], unique=False)
    op.create_table('target_talent',
    sa.Column('talent_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('talent_name', sa.String(length=100), nullable=False, comment='장기자랑 이름 (예: 기타 연주)'),
    sa.Column('gender_filter', sa.String(length=10), nullable=False, comment='매칭될 성별 (male/female)'),
    sa.Column('target_image_path', sa.String(length=512), nullable=False, comment='딥페이크 합성에 사용될 타겟 이미지 경로'),
    sa.PrimaryKeyConstraint('talent_id'),
    sa.UniqueConstraint('talent_name')
    )
    op.create_index(op.f('ix_target_talent_talent_id'), 'target_talent', ['talent_id'], unique=False)
    op.create_table('participation',
    sa.Column('participation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consent_agreed', sa.Boolean(), nullable=False, comment='개인정보 수집/이용 동의 여부'),
    sa.Column('gender', sa.String(length=10), nullable=False, comment='사용자가 선택한 성별 (male/female)'),
    sa.Column('original_image_path', sa.String(length=512), nullable=False, comment='키오스크에서 촬영한 원본 사진 경로'),
    sa.Column('selected_profile_id', sa.Integer(), nullable=True, comment='배정된 프로필 ID (예: 광수)'),
    sa.Column('selected_talent_id', sa.Integer(), nullable=True, comment='배정된 장기자랑 ID (예: 기타 연주)'),
    sa.Column('generated_profile_image_path', sa.String(length=512), nullable=True, comment='최종 생성된 프로필 합성 이미지 경로'),
    sa.Column('generated_talent_image_path', sa.String(length=512), nullable=True, comment='최종 생성된 장기자랑 합성 이미지 경로'),
    sa.Column('download_page_uuid', sa.String(length=36), nullable=False, comment='QR코드 다운로드 페이지 고유 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='세션 생성 시각'),
    sa.ForeignKeyConstraint(['selected_profile_id'], ['target_profile.profile_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selected_talent_id'], ['target_talent.talent_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('participation_id'),
    sa.UniqueConstraint('download_page_uuid')
    )
    op.create_index(op.f('ix_participation_participation_id'), 'participation', ['participation_id'], unique=False)
    op.create_table('print_log',
    sa.Column('print_log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('participation_id', sa.Integer(), nullable=False, comment='어떤 체험 세션인지 식별'),
    sa.Column('image_type', sa.String(length=20), nullable=False, comment="'profile' 또는 'talent' 인쇄 여부"),
    sa.Column('printed_at', sa.DateTime(), nullable=False, comment='인쇄한 시각'),
    sa.ForeignKeyConstraint(['participation_id'], ['participation.participation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('print_log_id')
    )
    op.create_index(op.f('ix_print_log_participation_id'), 'print_log', ['participation_id'], unique=False)
    op.create_index(op.f('ix_print_log_print_log_id'), 'print_log', ['print_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_print_log_print_log_id'), table_name='print_log')
    op.drop_index(op.f('ix_print_log_participation_id'), table_name='print_log')
    op.drop_table('print_log')
    op.drop_index(op.f('ix_participation_participation_id'), table_name='participation')
    op.drop_table('participation')
    op.drop_index(op.f('ix_target_talent_talent_id'), table_name='target_talent')
    op.drop_table('target_talent')
    op.drop_index(op.f('ix_target_profile_profile_id'), table_name='target_profile')
    op.drop_table('target_profile')
    # ### end Alembic commands ###
